/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BookService } from "../book.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BookCreateInput } from "./BookCreateInput";
import { Book } from "./Book";
import { BookFindManyArgs } from "./BookFindManyArgs";
import { BookWhereUniqueInput } from "./BookWhereUniqueInput";
import { BookUpdateInput } from "./BookUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BookControllerBase {
  constructor(
    protected readonly service: BookService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Book })
  @nestAccessControl.UseRoles({
    resource: "Book",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: BookCreateInput,
  })
  async createBook(@common.Body() data: BookCreateInput): Promise<Book> {
    return await this.service.createBook({
      data: {
        ...data,

        author: data.author
          ? {
              connect: data.author,
            }
          : undefined,

        category: data.category
          ? {
              connect: data.category,
            }
          : undefined,
      },
      select: {
        author: {
          select: {
            id: true,
          },
        },

        category: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        isbn: true,
        publishedDate: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Book] })
  @ApiNestedQuery(BookFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Book",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async books(@common.Req() request: Request): Promise<Book[]> {
    const args = plainToClass(BookFindManyArgs, request.query);
    return this.service.books({
      ...args,
      select: {
        author: {
          select: {
            id: true,
          },
        },

        category: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        isbn: true,
        publishedDate: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Book })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Book",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async book(
    @common.Param() params: BookWhereUniqueInput
  ): Promise<Book | null> {
    const result = await this.service.book({
      where: params,
      select: {
        author: {
          select: {
            id: true,
          },
        },

        category: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        isbn: true,
        publishedDate: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Book })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Book",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: BookUpdateInput,
  })
  async updateBook(
    @common.Param() params: BookWhereUniqueInput,
    @common.Body() data: BookUpdateInput
  ): Promise<Book | null> {
    try {
      return await this.service.updateBook({
        where: params,
        data: {
          ...data,

          author: data.author
            ? {
                connect: data.author,
              }
            : undefined,

          category: data.category
            ? {
                connect: data.category,
              }
            : undefined,
        },
        select: {
          author: {
            select: {
              id: true,
            },
          },

          category: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          isbn: true,
          publishedDate: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Book })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Book",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBook(
    @common.Param() params: BookWhereUniqueInput
  ): Promise<Book | null> {
    try {
      return await this.service.deleteBook({
        where: params,
        select: {
          author: {
            select: {
              id: true,
            },
          },

          category: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          isbn: true,
          publishedDate: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
